sonar.projectKey=meyer-pidiache_yt-reader-mode
sonar.organization=meyer-pidiache

sonar.projectName=yt-reader-mode

sonar.sources=src,popup
sonar.exclusions=**/*.test.*
sonar.coverage.exclusions=src/ui/toggleButton.js,src/services/panelManager.js,src/core/youtubeFacade.js

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
